### ISSUE TITLE
Investigate pdfplumber pdf error during event scrape

### ISSUE THREAD

**Issue by xmedr** [Metro-Records/scrapers-lametro#31]
We've been getting this [PDFSyntax error from pdfplumber in Sentry](https://datamade.sentry.io/issues/5939457946/events/cdfdb22eb2d84fcdbfc22669ed679578/events/?project=4504447849201664&sort=-environment) since adding that logging in #29 (so, good confirmation that that change is reporting errors as expected). From those logs, it seems to be a different pdf causing it each time which leads me to believe that these are just temporary hitches. A pdf that triggers this error today, will most likely work just fine tomorrow. It could not encounter the error at all next time or a different pdf might cause it. This seems to be a known issue with one of its dependencies: https://github.com/pdfminer/pdfminer.six/issues/476

I'm thinking of two options. What do you think @antidipyramid:
- Since these attachments get checked multiple times, it would have its chance to be checked again. We could change the sentry report to be a warning instead of an error if possible, and let it retry naturally next time.
- We could try to repair the pdf when this error is raised with something similar to [this comment in that mentioned issue](https://github.com/pdfminer/pdfminer.six/issues/476#issuecomment-1840856199). We'd probably copy the pdf into memory in order to repair it and retry the extraction on that memory copy, instead of actually writing a new one.

The event scrapes have continued on to succeed every time so this doesn't seem to be an urgent issue, but it is a frequent one.

**Comment by antidipyramid** [comment]
If this error doesn't cause a persistent issue when handling certain PDFs, I think sending message to Sentry as a warning is reasonable.
